### ISSUE TITLE
It is supported by Raspberry Pi?

### ISSUE THREAD

**Issue by pedrofelipest** [alex-sherman/python-mrpc#1]
Greetings.

I'm creating a mesh network with raspberry, is your implementation capable of making them exchange information?

**Comment by alex-sherman** [comment]
This implementation definitely runs on Raspberry Pi, in fact I think that's the only place I use it at the moment. However, my caveat would be that there is nothing in this library to directly facilitate building a mesh network. It's mostly just to provide a layer on top of an already existing mesh network, making it easier to address individual or groups of nodes, and accessing the services that those nodes support.

If you already have a mesh network and you want a clean-ish way to communicate with the nodes, this library might be a good fit.

**Comment by pedrofelipest** [comment]
Thanks, I'm testing some mesh network deployments at the moment. Do you have any suggestion. I used https://github.com/urlgrey/hsmm-pi and https://www.open-mesh.org/projects/batman-adv/wiki/Wiki.
